DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , BIRTH_DATE DATE
     , DESCRIPTION VARCHAR(2000)
     , PHOTO BLOB
     , VERSION INT NOT NULL DEFAULT 0
     , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
     , PRIMARY KEY (ID)
);

CREATE TABLE posts (
      id INT NOT NULL AUTO_INCREMENT
     , title VARCHAR(100) NOT NULL
     , version INT NOT NULL DEFAULT 0
     , UNIQUE UQ_POST_1 (title)
     , PRIMARY KEY (id)
);

CREATE TABLE comments (
      id INT NOT NULL AUTO_INCREMENT
     , post_id INT NOT NULL
     , text VARCHAR(250) NOT NULL
     , version INT NOT NULL DEFAULT 0
     , UNIQUE UQ_COMMNENT_1 (text)
     , PRIMARY KEY (id)
);
